# Generated by Django 5.2.2 on 2025-06-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='maintenance_mode',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_name',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hel_text',
            field=models.CharField(null=True, verbose_name='Yordam teksti'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hel_video_url',
            field=models.URLField(null=True, verbose_name='Yordam video havola'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_url',
            field=models.URLField(null=True, verbose_name='Ustoz telegrami'),
        ),
    ]
