# Generated by Django 5.2.2 on 2025-06-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_sitesettings_maintenance_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='hel_text',
            field=models.TextField(blank=True, null=True, verbose_name='Yordam teksti'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hel_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Yordam video havola'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ustoz telegrami'),
        ),
    ]
