# Generated by Django 5.2.2 on 2025-06-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_sitesettings_hel_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='hel_video_url',
            field=models.CharField(blank=True, null=True, verbose_name='Yordam video havola'),
        ),
    ]
