# Generated by Django 5.2.2 on 2025-06-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_sitesettings_hel_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='hel_video_url',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hel_video_id',
            field=models.CharField(blank=True, null=True, verbose_name='Yordam youtube video id'),
        ),
    ]
