# Generated by Django 5.2.2 on 2025-06-11 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_sitesettings_hel_video_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='hel_video_id',
            new_name='help_video_id',
        ),
    ]
