# Generated by Django 5.2.2 on 2025-06-11 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_hel_video_id_sitesettings_help_video_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='hel_text',
            new_name='help_text',
        ),
    ]
