# Generated by Django 5.2.2 on 2025-06-11 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_tag_myuser_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='tg_id',
        ),
    ]
