# Generated by Django 5.2.2 on 2025-06-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0010_remove_myuser_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='main_user_groups', related_query_name='main_user_group', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='main_user_permissions', related_query_name='main_user_permission', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
