# Generated by Django 5.2.2 on 2025-06-11 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_myuser_groups_alter_myuser_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
