# Generated by Django 5.2.2 on 2025-06-11 06:59

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_post_author_delete_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
