# Generated by Django 5.2.2 on 2025-06-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_info',
            field=models.CharField(default='', verbose_name='qisqa tarifi'),
        ),
    ]
