# Generated by Django 5.2.2 on 2025-07-02 19:14

import django.db.models.deletion
import django.utils.timezone
import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='nomi')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='nomi')),
                ('slug', models.SlugField(unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='rasm')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='courses', to='courses.group', verbose_name='guruhlar')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nomi')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moduls', to='courses.course', verbose_name='kurs')),
            ],
            options={
                'verbose_name': 'Modul',
                'verbose_name_plural': 'Modullar',
                'unique_together': {('course', 'name'), ('course', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nomi')),
                ('slug', models.SlugField(max_length=255)),
                ('description', django_quill.fields.QuillField(verbose_name='Dars kontenti')),
                ('modul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.modul', verbose_name='Modul')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['modul__pk', 'pk'],
                'unique_together': {('modul', 'name'), ('modul', 'slug')},
            },
        ),
    ]
