# Generated by Django 5.2.2 on 2025-07-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['modul__pk', 'pk'], 'verbose_name': 'Dars', 'verbose_name_plural': 'Darslar'},
        ),
        migrations.AlterField(
            model_name='modul',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
