# Generated by Django 5.2.2 on 2025-07-02 17:02

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_lesson_options_alter_modul_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=django_quill.fields.QuillField(verbose_name='Dars kontenti'),
        ),
    ]
