# Generated by Django 5.2.2 on 2025-06-13 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lesson_options_alter_lesson_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nomi')),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Modul',
                'verbose_name_plural': 'Modullar',
            },
        ),
        migrations.RemoveConstraint(
            model_name='lesson',
            name='unique_lesson_name_per_course',
        ),
        migrations.RemoveConstraint(
            model_name='lesson',
            name='unique_lesson_slug_per_course',
        ),
        migrations.AddField(
            model_name='modul',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moduls', to='courses.course', verbose_name='kurs'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='modul',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.modul', verbose_name='Modul'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('modul', 'name'), ('modul', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='modul',
            unique_together={('course', 'name'), ('course', 'slug')},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
    ]
